### ISSUE TITLE
c movai

### ISSUE THREAD

**Issue by error7404** [B2KServices/CringeBot#22]
le bot il es movai est pa drol

svp fix

**Comment by Gwilhoa** [comment]
Bonjour monsieur @error7404 je comprend que mon code peut choquer certaines personne mais comment pourrais-je l'améliorer si vous ne donnez aucune piste d'améliorations ? Honnêtement soyez sérieux de temps en temps et faites des critiques constructives

**Comment by error7404** [comment]
ba il es pas drol

repare votr umour svp

**Comment by error7404** [comment]
CENSURE!!!!!!
